#!/usr/bin/bash

echo "$0" $@ 1>&2

if [ "$1" != "upgrade" -a "$1" != "remove" -a "$1" != "purge" ] ; then
    exit
fi

for fn in /etc/ufw/after{,6}.rules ; do
    mv "$fn" "$fn.bak"
    cat "$fn.bak" | grep -v wg0 | sed -e 'H' -e '/^\*filter/d' -e '/^$/d' -e 's/.*//;x;s/^\n//' -e '/^\n*\*filter\s*\nCOMMIT/d' | sed -e 'H' -e '/^\*nat/d' -e '/^$/d' -e 's/.*//;x;s/^\n//' -e '/^\n*\*nat\s*\nCOMMIT/d' > "$fn"
done

if [ "$1" = "purge" ] ; then
    for fn in /etc/systemd/network/990-wg0.netdev.d/*.conf ; do
        rm "$fn"
    done
    [ -f /var/tmp/wgadm_pwdhash.bin ] && rm /var/tmp/wgadm_pwdhash.bin
    [ -f /var/tmp/wgadm_jwt_key.bin ] && rm /var/tmp/wgadm_jwt_key.bin
fi

ufw reload

systemctl daemon-reload
systemctl restart systemd-networkd
sysctl net.ipv4.ip_forward=0
sysctl net.ipv6.conf.all.forwarding=0
sysctl --system

exit 0
